// @generated by protobuf-ts 1.0.13 with parameters long_type_string,optimize_code_size,generate_dependencies
// @generated from protobuf file "chat/v1/emotes.proto" (package "protocol.chat.v1", syntax proto3)
// tslint:disable
import { MessageType } from "@protobuf-ts/runtime";
/**
 * @generated from protobuf message protocol.chat.v1.CreateEmotePackRequest
 */
export interface CreateEmotePackRequest {
  /**
   * @generated from protobuf field: string pack_name = 1;
   */
  packName: string;
}
/**
 * @generated from protobuf message protocol.chat.v1.CreateEmotePackResponse
 */
export interface CreateEmotePackResponse {
  /**
   * @generated from protobuf field: uint64 pack_id = 1 [jstype = JS_STRING];
   */
  packId: string;
}
/**
 * @generated from protobuf message protocol.chat.v1.GetEmotePacksRequest
 */
export interface GetEmotePacksRequest {}
/**
 * @generated from protobuf message protocol.chat.v1.GetEmotePacksResponse
 */
export interface GetEmotePacksResponse {
  /**
   * @generated from protobuf field: repeated protocol.chat.v1.GetEmotePacksResponse.EmotePack packs = 1;
   */
  packs: GetEmotePacksResponse_EmotePack[];
}
/**
 * @generated from protobuf message protocol.chat.v1.GetEmotePacksResponse.EmotePack
 */
export interface GetEmotePacksResponse_EmotePack {
  /**
   * @generated from protobuf field: uint64 pack_id = 1 [jstype = JS_STRING];
   */
  packId: string;
  /**
   * @generated from protobuf field: uint64 pack_owner = 2 [jstype = JS_STRING];
   */
  packOwner: string;
  /**
   * @generated from protobuf field: string pack_name = 3;
   */
  packName: string;
}
/**
 * @generated from protobuf message protocol.chat.v1.GetEmotePackEmotesRequest
 */
export interface GetEmotePackEmotesRequest {
  /**
   * @generated from protobuf field: uint64 pack_id = 1 [jstype = JS_STRING];
   */
  packId: string;
}
/**
 * @generated from protobuf message protocol.chat.v1.GetEmotePackEmotesResponse
 */
export interface GetEmotePackEmotesResponse {
  /**
   * @generated from protobuf field: repeated protocol.chat.v1.GetEmotePackEmotesResponse.Emote emotes = 1;
   */
  emotes: GetEmotePackEmotesResponse_Emote[];
}
/**
 * @generated from protobuf message protocol.chat.v1.GetEmotePackEmotesResponse.Emote
 */
export interface GetEmotePackEmotesResponse_Emote {
  /**
   * @generated from protobuf field: string image_id = 1;
   */
  imageId: string;
  /**
   * @generated from protobuf field: string name = 2;
   */
  name: string;
}
/**
 * @generated from protobuf message protocol.chat.v1.AddEmoteToPackRequest
 */
export interface AddEmoteToPackRequest {
  /**
   * @generated from protobuf field: uint64 pack_id = 1 [jstype = JS_STRING];
   */
  packId: string;
  /**
   * @generated from protobuf field: string image_id = 2;
   */
  imageId: string;
  /**
   * @generated from protobuf field: string name = 3;
   */
  name: string;
}
/**
 * @generated from protobuf message protocol.chat.v1.DeleteEmoteFromPackRequest
 */
export interface DeleteEmoteFromPackRequest {
  /**
   * @generated from protobuf field: uint64 pack_id = 1 [jstype = JS_STRING];
   */
  packId: string;
  /**
   * @generated from protobuf field: string image_id = 2;
   */
  imageId: string;
}
/**
 * @generated from protobuf message protocol.chat.v1.DeleteEmotePackRequest
 */
export interface DeleteEmotePackRequest {
  /**
   * @generated from protobuf field: uint64 pack_id = 1 [jstype = JS_STRING];
   */
  packId: string;
}
/**
 * @generated from protobuf message protocol.chat.v1.DequipEmotePackRequest
 */
export interface DequipEmotePackRequest {
  /**
   * @generated from protobuf field: uint64 pack_id = 1 [jstype = JS_STRING];
   */
  packId: string;
}
/**
 * @generated from protobuf message protocol.chat.v1.EquipEmotePackRequest
 */
export interface EquipEmotePackRequest {
  /**
   * @generated from protobuf field: uint64 pack_id = 1 [jstype = JS_STRING];
   */
  packId: string;
}
/**
 * Type for protobuf message protocol.chat.v1.CreateEmotePackRequest
 */
class CreateEmotePackRequest$Type extends MessageType<CreateEmotePackRequest> {
  constructor() {
    super("protocol.chat.v1.CreateEmotePackRequest", [
      { no: 1, name: "pack_name", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
    ]);
  }
}
export const CreateEmotePackRequest = new CreateEmotePackRequest$Type();
/**
 * Type for protobuf message protocol.chat.v1.CreateEmotePackResponse
 */
class CreateEmotePackResponse$Type extends MessageType<CreateEmotePackResponse> {
  constructor() {
    super("protocol.chat.v1.CreateEmotePackResponse", [
      { no: 1, name: "pack_id", kind: "scalar", T: 4 /*ScalarType.UINT64*/ },
    ]);
  }
}
export const CreateEmotePackResponse = new CreateEmotePackResponse$Type();
/**
 * Type for protobuf message protocol.chat.v1.GetEmotePacksRequest
 */
class GetEmotePacksRequest$Type extends MessageType<GetEmotePacksRequest> {
  constructor() {
    super("protocol.chat.v1.GetEmotePacksRequest", []);
  }
}
export const GetEmotePacksRequest = new GetEmotePacksRequest$Type();
/**
 * Type for protobuf message protocol.chat.v1.GetEmotePacksResponse
 */
class GetEmotePacksResponse$Type extends MessageType<GetEmotePacksResponse> {
  constructor() {
    super("protocol.chat.v1.GetEmotePacksResponse", [
      {
        no: 1,
        name: "packs",
        kind: "message",
        repeat: 1 /*RepeatType.PACKED*/,
        T: () => GetEmotePacksResponse_EmotePack,
      },
    ]);
  }
}
export const GetEmotePacksResponse = new GetEmotePacksResponse$Type();
/**
 * Type for protobuf message protocol.chat.v1.GetEmotePacksResponse.EmotePack
 */
class GetEmotePacksResponse_EmotePack$Type extends MessageType<GetEmotePacksResponse_EmotePack> {
  constructor() {
    super("protocol.chat.v1.GetEmotePacksResponse.EmotePack", [
      { no: 1, name: "pack_id", kind: "scalar", T: 4 /*ScalarType.UINT64*/ },
      { no: 2, name: "pack_owner", kind: "scalar", T: 4 /*ScalarType.UINT64*/ },
      { no: 3, name: "pack_name", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
    ]);
  }
}
export const GetEmotePacksResponse_EmotePack =
  new GetEmotePacksResponse_EmotePack$Type();
/**
 * Type for protobuf message protocol.chat.v1.GetEmotePackEmotesRequest
 */
class GetEmotePackEmotesRequest$Type extends MessageType<GetEmotePackEmotesRequest> {
  constructor() {
    super("protocol.chat.v1.GetEmotePackEmotesRequest", [
      { no: 1, name: "pack_id", kind: "scalar", T: 4 /*ScalarType.UINT64*/ },
    ]);
  }
}
export const GetEmotePackEmotesRequest = new GetEmotePackEmotesRequest$Type();
/**
 * Type for protobuf message protocol.chat.v1.GetEmotePackEmotesResponse
 */
class GetEmotePackEmotesResponse$Type extends MessageType<GetEmotePackEmotesResponse> {
  constructor() {
    super("protocol.chat.v1.GetEmotePackEmotesResponse", [
      {
        no: 1,
        name: "emotes",
        kind: "message",
        repeat: 1 /*RepeatType.PACKED*/,
        T: () => GetEmotePackEmotesResponse_Emote,
      },
    ]);
  }
}
export const GetEmotePackEmotesResponse = new GetEmotePackEmotesResponse$Type();
/**
 * Type for protobuf message protocol.chat.v1.GetEmotePackEmotesResponse.Emote
 */
class GetEmotePackEmotesResponse_Emote$Type extends MessageType<GetEmotePackEmotesResponse_Emote> {
  constructor() {
    super("protocol.chat.v1.GetEmotePackEmotesResponse.Emote", [
      { no: 1, name: "image_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
      { no: 2, name: "name", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
    ]);
  }
}
export const GetEmotePackEmotesResponse_Emote =
  new GetEmotePackEmotesResponse_Emote$Type();
/**
 * Type for protobuf message protocol.chat.v1.AddEmoteToPackRequest
 */
class AddEmoteToPackRequest$Type extends MessageType<AddEmoteToPackRequest> {
  constructor() {
    super("protocol.chat.v1.AddEmoteToPackRequest", [
      { no: 1, name: "pack_id", kind: "scalar", T: 4 /*ScalarType.UINT64*/ },
      { no: 2, name: "image_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
      { no: 3, name: "name", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
    ]);
  }
}
export const AddEmoteToPackRequest = new AddEmoteToPackRequest$Type();
/**
 * Type for protobuf message protocol.chat.v1.DeleteEmoteFromPackRequest
 */
class DeleteEmoteFromPackRequest$Type extends MessageType<DeleteEmoteFromPackRequest> {
  constructor() {
    super("protocol.chat.v1.DeleteEmoteFromPackRequest", [
      { no: 1, name: "pack_id", kind: "scalar", T: 4 /*ScalarType.UINT64*/ },
      { no: 2, name: "image_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
    ]);
  }
}
export const DeleteEmoteFromPackRequest = new DeleteEmoteFromPackRequest$Type();
/**
 * Type for protobuf message protocol.chat.v1.DeleteEmotePackRequest
 */
class DeleteEmotePackRequest$Type extends MessageType<DeleteEmotePackRequest> {
  constructor() {
    super("protocol.chat.v1.DeleteEmotePackRequest", [
      { no: 1, name: "pack_id", kind: "scalar", T: 4 /*ScalarType.UINT64*/ },
    ]);
  }
}
export const DeleteEmotePackRequest = new DeleteEmotePackRequest$Type();
/**
 * Type for protobuf message protocol.chat.v1.DequipEmotePackRequest
 */
class DequipEmotePackRequest$Type extends MessageType<DequipEmotePackRequest> {
  constructor() {
    super("protocol.chat.v1.DequipEmotePackRequest", [
      { no: 1, name: "pack_id", kind: "scalar", T: 4 /*ScalarType.UINT64*/ },
    ]);
  }
}
export const DequipEmotePackRequest = new DequipEmotePackRequest$Type();
/**
 * Type for protobuf message protocol.chat.v1.EquipEmotePackRequest
 */
class EquipEmotePackRequest$Type extends MessageType<EquipEmotePackRequest> {
  constructor() {
    super("protocol.chat.v1.EquipEmotePackRequest", [
      { no: 1, name: "pack_id", kind: "scalar", T: 4 /*ScalarType.UINT64*/ },
    ]);
  }
}
export const EquipEmotePackRequest = new EquipEmotePackRequest$Type();
