// @generated by protobuf-ts 1.0.12 with parameters long_type_string,optimize_code_size,generate_dependencies
// @generated from protobuf file "chat/v1/guilds.proto" (package "protocol.chat.v1", syntax proto3)
// tslint:disable
import { MessageType } from "@protobuf-ts/runtime";
import { Metadata } from "../../harmonytypes/v1/types";
/**
 * @generated from protobuf message protocol.chat.v1.CreateGuildRequest
 */
export interface CreateGuildRequest {
  /**
   * @generated from protobuf field: protocol.harmonytypes.v1.Metadata metadata = 3;
   */
  metadata?: Metadata;
  /**
   * @generated from protobuf field: string guild_name = 1;
   */
  guildName: string;
  /**
   * @generated from protobuf field: string picture_url = 2;
   */
  pictureUrl: string;
}
/**
 * @generated from protobuf message protocol.chat.v1.CreateGuildResponse
 */
export interface CreateGuildResponse {
  /**
   * @generated from protobuf field: uint64 guild_id = 1;
   */
  guildId: string;
}
/**
 * @generated from protobuf message protocol.chat.v1.CreateInviteRequest
 */
export interface CreateInviteRequest {
  /**
   * @generated from protobuf field: uint64 guild_id = 1;
   */
  guildId: string;
  /**
   * @generated from protobuf field: string name = 2;
   */
  name: string;
  /**
   * @generated from protobuf field: int32 possible_uses = 3;
   */
  possibleUses: number;
}
/**
 * @generated from protobuf message protocol.chat.v1.CreateInviteResponse
 */
export interface CreateInviteResponse {
  /**
   * @generated from protobuf field: string name = 1;
   */
  name: string;
}
/**
 * @generated from protobuf message protocol.chat.v1.GetGuildListRequest
 */
export interface GetGuildListRequest {}
/**
 * @generated from protobuf message protocol.chat.v1.GetGuildListResponse
 */
export interface GetGuildListResponse {
  /**
   * @generated from protobuf field: repeated protocol.chat.v1.GetGuildListResponse.GuildListEntry guilds = 1;
   */
  guilds: GetGuildListResponse_GuildListEntry[];
}
/**
 * @generated from protobuf message protocol.chat.v1.GetGuildListResponse.GuildListEntry
 */
export interface GetGuildListResponse_GuildListEntry {
  /**
   * @generated from protobuf field: uint64 guild_id = 1;
   */
  guildId: string;
  /**
   * @generated from protobuf field: string host = 2;
   */
  host: string;
}
/**
 * @generated from protobuf message protocol.chat.v1.GetGuildRequest
 */
export interface GetGuildRequest {
  /**
   * @generated from protobuf field: uint64 guild_id = 1;
   */
  guildId: string;
}
/**
 * @generated from protobuf message protocol.chat.v1.GetGuildResponse
 */
export interface GetGuildResponse {
  /**
   * @generated from protobuf field: protocol.harmonytypes.v1.Metadata metadata = 4;
   */
  metadata?: Metadata;
  /**
   * @generated from protobuf field: string guild_name = 1;
   */
  guildName: string;
  /**
   * @generated from protobuf field: uint64 guild_owner = 2;
   */
  guildOwner: string;
  /**
   * @generated from protobuf field: string guild_picture = 3;
   */
  guildPicture: string;
}
/**
 * @generated from protobuf message protocol.chat.v1.GetGuildInvitesRequest
 */
export interface GetGuildInvitesRequest {
  /**
   * @generated from protobuf field: uint64 guild_id = 1;
   */
  guildId: string;
}
/**
 * @generated from protobuf message protocol.chat.v1.GetGuildInvitesResponse
 */
export interface GetGuildInvitesResponse {
  /**
   * @generated from protobuf field: repeated protocol.chat.v1.GetGuildInvitesResponse.Invite invites = 1;
   */
  invites: GetGuildInvitesResponse_Invite[];
}
/**
 * @generated from protobuf message protocol.chat.v1.GetGuildInvitesResponse.Invite
 */
export interface GetGuildInvitesResponse_Invite {
  /**
   * @generated from protobuf field: string invite_id = 1;
   */
  inviteId: string;
  /**
   * @generated from protobuf field: int32 possible_uses = 2;
   */
  possibleUses: number;
  /**
   * @generated from protobuf field: int32 use_count = 3;
   */
  useCount: number;
}
/**
 * @generated from protobuf message protocol.chat.v1.GetGuildMembersRequest
 */
export interface GetGuildMembersRequest {
  /**
   * @generated from protobuf field: uint64 guild_id = 1;
   */
  guildId: string;
}
/**
 * @generated from protobuf message protocol.chat.v1.GetGuildMembersResponse
 */
export interface GetGuildMembersResponse {
  /**
   * @generated from protobuf field: repeated uint64 members = 1;
   */
  members: string[];
}
/**
 * @generated from protobuf message protocol.chat.v1.UpdateGuildInformationRequest
 */
export interface UpdateGuildInformationRequest {
  /**
   * @generated from protobuf field: uint64 guild_id = 1;
   */
  guildId: string;
  /**
   * @generated from protobuf field: string new_guild_name = 2;
   */
  newGuildName: string;
  /**
   * @generated from protobuf field: bool update_guild_name = 3;
   */
  updateGuildName: boolean;
  /**
   * @generated from protobuf field: string new_guild_picture = 4;
   */
  newGuildPicture: string;
  /**
   * @generated from protobuf field: bool update_guild_picture = 5;
   */
  updateGuildPicture: boolean;
  /**
   * @generated from protobuf field: protocol.harmonytypes.v1.Metadata metadata = 6;
   */
  metadata?: Metadata;
  /**
   * @generated from protobuf field: bool update_metadata = 7;
   */
  updateMetadata: boolean;
}
/**
 * @generated from protobuf message protocol.chat.v1.DeleteGuildRequest
 */
export interface DeleteGuildRequest {
  /**
   * @generated from protobuf field: uint64 guild_id = 1;
   */
  guildId: string;
}
/**
 * @generated from protobuf message protocol.chat.v1.DeleteInviteRequest
 */
export interface DeleteInviteRequest {
  /**
   * @generated from protobuf field: uint64 guild_id = 1;
   */
  guildId: string;
  /**
   * @generated from protobuf field: string invite_id = 2;
   */
  inviteId: string;
}
/**
 * @generated from protobuf message protocol.chat.v1.JoinGuildRequest
 */
export interface JoinGuildRequest {
  /**
   * @generated from protobuf field: string invite_id = 1;
   */
  inviteId: string;
}
/**
 * @generated from protobuf message protocol.chat.v1.JoinGuildResponse
 */
export interface JoinGuildResponse {
  /**
   * @generated from protobuf field: uint64 guild_id = 1;
   */
  guildId: string;
}
/**
 * @generated from protobuf message protocol.chat.v1.PreviewGuildRequest
 */
export interface PreviewGuildRequest {
  /**
   * @generated from protobuf field: string invite_id = 1;
   */
  inviteId: string;
}
/**
 * @generated from protobuf message protocol.chat.v1.PreviewGuildResponse
 */
export interface PreviewGuildResponse {
  /**
   * @generated from protobuf field: string name = 1;
   */
  name: string;
  /**
   * @generated from protobuf field: string avatar = 2;
   */
  avatar: string;
  /**
   * @generated from protobuf field: uint64 member_count = 3;
   */
  memberCount: string;
}
/**
 * @generated from protobuf message protocol.chat.v1.LeaveGuildRequest
 */
export interface LeaveGuildRequest {
  /**
   * @generated from protobuf field: uint64 guild_id = 1;
   */
  guildId: string;
}
/**
 * GUILD LIST
 *
 * @generated from protobuf message protocol.chat.v1.AddGuildToGuildListRequest
 */
export interface AddGuildToGuildListRequest {
  /**
   * @generated from protobuf field: uint64 guild_id = 1;
   */
  guildId: string;
  /**
   * @generated from protobuf field: string homeserver = 2;
   */
  homeserver: string;
}
/**
 * @generated from protobuf message protocol.chat.v1.AddGuildToGuildListResponse
 */
export interface AddGuildToGuildListResponse {}
/**
 * @generated from protobuf message protocol.chat.v1.RemoveGuildFromGuildListRequest
 */
export interface RemoveGuildFromGuildListRequest {
  /**
   * @generated from protobuf field: uint64 guild_id = 1;
   */
  guildId: string;
  /**
   * @generated from protobuf field: string homeserver = 2;
   */
  homeserver: string;
}
/**
 * @generated from protobuf message protocol.chat.v1.RemoveGuildFromGuildListResponse
 */
export interface RemoveGuildFromGuildListResponse {}
/**
 * @generated from protobuf message protocol.chat.v1.BanUserRequest
 */
export interface BanUserRequest {
  /**
   * @generated from protobuf field: uint64 guild_id = 1;
   */
  guildId: string;
  /**
   * @generated from protobuf field: uint64 user_id = 2;
   */
  userId: string;
}
/**
 * @generated from protobuf message protocol.chat.v1.KickUserRequest
 */
export interface KickUserRequest {
  /**
   * @generated from protobuf field: uint64 guild_id = 1;
   */
  guildId: string;
  /**
   * @generated from protobuf field: uint64 user_id = 2;
   */
  userId: string;
}
/**
 * @generated from protobuf message protocol.chat.v1.UnbanUserRequest
 */
export interface UnbanUserRequest {
  /**
   * @generated from protobuf field: uint64 guild_id = 1;
   */
  guildId: string;
  /**
   * @generated from protobuf field: uint64 user_id = 2;
   */
  userId: string;
}
/**
 * Type for protobuf message protocol.chat.v1.CreateGuildRequest
 */
class CreateGuildRequest$Type extends MessageType<CreateGuildRequest> {
  constructor() {
    super("protocol.chat.v1.CreateGuildRequest", [
      { no: 3, name: "metadata", kind: "message", T: () => Metadata },
      { no: 1, name: "guild_name", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
      {
        no: 2,
        name: "picture_url",
        kind: "scalar",
        T: 9 /*ScalarType.STRING*/,
      },
    ]);
  }
}
export const CreateGuildRequest = new CreateGuildRequest$Type();
/**
 * Type for protobuf message protocol.chat.v1.CreateGuildResponse
 */
class CreateGuildResponse$Type extends MessageType<CreateGuildResponse> {
  constructor() {
    super("protocol.chat.v1.CreateGuildResponse", [
      { no: 1, name: "guild_id", kind: "scalar", T: 4 /*ScalarType.UINT64*/ },
    ]);
  }
}
export const CreateGuildResponse = new CreateGuildResponse$Type();
/**
 * Type for protobuf message protocol.chat.v1.CreateInviteRequest
 */
class CreateInviteRequest$Type extends MessageType<CreateInviteRequest> {
  constructor() {
    super("protocol.chat.v1.CreateInviteRequest", [
      { no: 1, name: "guild_id", kind: "scalar", T: 4 /*ScalarType.UINT64*/ },
      { no: 2, name: "name", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
      {
        no: 3,
        name: "possible_uses",
        kind: "scalar",
        T: 5 /*ScalarType.INT32*/,
      },
    ]);
  }
}
export const CreateInviteRequest = new CreateInviteRequest$Type();
/**
 * Type for protobuf message protocol.chat.v1.CreateInviteResponse
 */
class CreateInviteResponse$Type extends MessageType<CreateInviteResponse> {
  constructor() {
    super("protocol.chat.v1.CreateInviteResponse", [
      { no: 1, name: "name", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
    ]);
  }
}
export const CreateInviteResponse = new CreateInviteResponse$Type();
/**
 * Type for protobuf message protocol.chat.v1.GetGuildListRequest
 */
class GetGuildListRequest$Type extends MessageType<GetGuildListRequest> {
  constructor() {
    super("protocol.chat.v1.GetGuildListRequest", []);
  }
}
export const GetGuildListRequest = new GetGuildListRequest$Type();
/**
 * Type for protobuf message protocol.chat.v1.GetGuildListResponse
 */
class GetGuildListResponse$Type extends MessageType<GetGuildListResponse> {
  constructor() {
    super("protocol.chat.v1.GetGuildListResponse", [
      {
        no: 1,
        name: "guilds",
        kind: "message",
        repeat: 1 /*RepeatType.PACKED*/,
        T: () => GetGuildListResponse_GuildListEntry,
      },
    ]);
  }
}
export const GetGuildListResponse = new GetGuildListResponse$Type();
/**
 * Type for protobuf message protocol.chat.v1.GetGuildListResponse.GuildListEntry
 */
class GetGuildListResponse_GuildListEntry$Type extends MessageType<GetGuildListResponse_GuildListEntry> {
  constructor() {
    super("protocol.chat.v1.GetGuildListResponse.GuildListEntry", [
      { no: 1, name: "guild_id", kind: "scalar", T: 4 /*ScalarType.UINT64*/ },
      { no: 2, name: "host", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
    ]);
  }
}
export const GetGuildListResponse_GuildListEntry = new GetGuildListResponse_GuildListEntry$Type();
/**
 * Type for protobuf message protocol.chat.v1.GetGuildRequest
 */
class GetGuildRequest$Type extends MessageType<GetGuildRequest> {
  constructor() {
    super("protocol.chat.v1.GetGuildRequest", [
      { no: 1, name: "guild_id", kind: "scalar", T: 4 /*ScalarType.UINT64*/ },
    ]);
  }
}
export const GetGuildRequest = new GetGuildRequest$Type();
/**
 * Type for protobuf message protocol.chat.v1.GetGuildResponse
 */
class GetGuildResponse$Type extends MessageType<GetGuildResponse> {
  constructor() {
    super("protocol.chat.v1.GetGuildResponse", [
      { no: 4, name: "metadata", kind: "message", T: () => Metadata },
      { no: 1, name: "guild_name", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
      {
        no: 2,
        name: "guild_owner",
        kind: "scalar",
        T: 4 /*ScalarType.UINT64*/,
      },
      {
        no: 3,
        name: "guild_picture",
        kind: "scalar",
        T: 9 /*ScalarType.STRING*/,
      },
    ]);
  }
}
export const GetGuildResponse = new GetGuildResponse$Type();
/**
 * Type for protobuf message protocol.chat.v1.GetGuildInvitesRequest
 */
class GetGuildInvitesRequest$Type extends MessageType<GetGuildInvitesRequest> {
  constructor() {
    super("protocol.chat.v1.GetGuildInvitesRequest", [
      { no: 1, name: "guild_id", kind: "scalar", T: 4 /*ScalarType.UINT64*/ },
    ]);
  }
}
export const GetGuildInvitesRequest = new GetGuildInvitesRequest$Type();
/**
 * Type for protobuf message protocol.chat.v1.GetGuildInvitesResponse
 */
class GetGuildInvitesResponse$Type extends MessageType<GetGuildInvitesResponse> {
  constructor() {
    super("protocol.chat.v1.GetGuildInvitesResponse", [
      {
        no: 1,
        name: "invites",
        kind: "message",
        repeat: 1 /*RepeatType.PACKED*/,
        T: () => GetGuildInvitesResponse_Invite,
      },
    ]);
  }
}
export const GetGuildInvitesResponse = new GetGuildInvitesResponse$Type();
/**
 * Type for protobuf message protocol.chat.v1.GetGuildInvitesResponse.Invite
 */
class GetGuildInvitesResponse_Invite$Type extends MessageType<GetGuildInvitesResponse_Invite> {
  constructor() {
    super("protocol.chat.v1.GetGuildInvitesResponse.Invite", [
      { no: 1, name: "invite_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
      {
        no: 2,
        name: "possible_uses",
        kind: "scalar",
        T: 5 /*ScalarType.INT32*/,
      },
      { no: 3, name: "use_count", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
    ]);
  }
}
export const GetGuildInvitesResponse_Invite = new GetGuildInvitesResponse_Invite$Type();
/**
 * Type for protobuf message protocol.chat.v1.GetGuildMembersRequest
 */
class GetGuildMembersRequest$Type extends MessageType<GetGuildMembersRequest> {
  constructor() {
    super("protocol.chat.v1.GetGuildMembersRequest", [
      { no: 1, name: "guild_id", kind: "scalar", T: 4 /*ScalarType.UINT64*/ },
    ]);
  }
}
export const GetGuildMembersRequest = new GetGuildMembersRequest$Type();
/**
 * Type for protobuf message protocol.chat.v1.GetGuildMembersResponse
 */
class GetGuildMembersResponse$Type extends MessageType<GetGuildMembersResponse> {
  constructor() {
    super("protocol.chat.v1.GetGuildMembersResponse", [
      {
        no: 1,
        name: "members",
        kind: "scalar",
        repeat: 1 /*RepeatType.PACKED*/,
        T: 4 /*ScalarType.UINT64*/,
      },
    ]);
  }
}
export const GetGuildMembersResponse = new GetGuildMembersResponse$Type();
/**
 * Type for protobuf message protocol.chat.v1.UpdateGuildInformationRequest
 */
class UpdateGuildInformationRequest$Type extends MessageType<UpdateGuildInformationRequest> {
  constructor() {
    super("protocol.chat.v1.UpdateGuildInformationRequest", [
      { no: 1, name: "guild_id", kind: "scalar", T: 4 /*ScalarType.UINT64*/ },
      {
        no: 2,
        name: "new_guild_name",
        kind: "scalar",
        T: 9 /*ScalarType.STRING*/,
      },
      {
        no: 3,
        name: "update_guild_name",
        kind: "scalar",
        T: 8 /*ScalarType.BOOL*/,
      },
      {
        no: 4,
        name: "new_guild_picture",
        kind: "scalar",
        T: 9 /*ScalarType.STRING*/,
      },
      {
        no: 5,
        name: "update_guild_picture",
        kind: "scalar",
        T: 8 /*ScalarType.BOOL*/,
      },
      { no: 6, name: "metadata", kind: "message", T: () => Metadata },
      {
        no: 7,
        name: "update_metadata",
        kind: "scalar",
        T: 8 /*ScalarType.BOOL*/,
      },
    ]);
  }
}
export const UpdateGuildInformationRequest = new UpdateGuildInformationRequest$Type();
/**
 * Type for protobuf message protocol.chat.v1.DeleteGuildRequest
 */
class DeleteGuildRequest$Type extends MessageType<DeleteGuildRequest> {
  constructor() {
    super("protocol.chat.v1.DeleteGuildRequest", [
      { no: 1, name: "guild_id", kind: "scalar", T: 4 /*ScalarType.UINT64*/ },
    ]);
  }
}
export const DeleteGuildRequest = new DeleteGuildRequest$Type();
/**
 * Type for protobuf message protocol.chat.v1.DeleteInviteRequest
 */
class DeleteInviteRequest$Type extends MessageType<DeleteInviteRequest> {
  constructor() {
    super("protocol.chat.v1.DeleteInviteRequest", [
      { no: 1, name: "guild_id", kind: "scalar", T: 4 /*ScalarType.UINT64*/ },
      { no: 2, name: "invite_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
    ]);
  }
}
export const DeleteInviteRequest = new DeleteInviteRequest$Type();
/**
 * Type for protobuf message protocol.chat.v1.JoinGuildRequest
 */
class JoinGuildRequest$Type extends MessageType<JoinGuildRequest> {
  constructor() {
    super("protocol.chat.v1.JoinGuildRequest", [
      { no: 1, name: "invite_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
    ]);
  }
}
export const JoinGuildRequest = new JoinGuildRequest$Type();
/**
 * Type for protobuf message protocol.chat.v1.JoinGuildResponse
 */
class JoinGuildResponse$Type extends MessageType<JoinGuildResponse> {
  constructor() {
    super("protocol.chat.v1.JoinGuildResponse", [
      { no: 1, name: "guild_id", kind: "scalar", T: 4 /*ScalarType.UINT64*/ },
    ]);
  }
}
export const JoinGuildResponse = new JoinGuildResponse$Type();
/**
 * Type for protobuf message protocol.chat.v1.PreviewGuildRequest
 */
class PreviewGuildRequest$Type extends MessageType<PreviewGuildRequest> {
  constructor() {
    super("protocol.chat.v1.PreviewGuildRequest", [
      { no: 1, name: "invite_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
    ]);
  }
}
export const PreviewGuildRequest = new PreviewGuildRequest$Type();
/**
 * Type for protobuf message protocol.chat.v1.PreviewGuildResponse
 */
class PreviewGuildResponse$Type extends MessageType<PreviewGuildResponse> {
  constructor() {
    super("protocol.chat.v1.PreviewGuildResponse", [
      { no: 1, name: "name", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
      { no: 2, name: "avatar", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
      {
        no: 3,
        name: "member_count",
        kind: "scalar",
        T: 4 /*ScalarType.UINT64*/,
      },
    ]);
  }
}
export const PreviewGuildResponse = new PreviewGuildResponse$Type();
/**
 * Type for protobuf message protocol.chat.v1.LeaveGuildRequest
 */
class LeaveGuildRequest$Type extends MessageType<LeaveGuildRequest> {
  constructor() {
    super("protocol.chat.v1.LeaveGuildRequest", [
      { no: 1, name: "guild_id", kind: "scalar", T: 4 /*ScalarType.UINT64*/ },
    ]);
  }
}
export const LeaveGuildRequest = new LeaveGuildRequest$Type();
/**
 * Type for protobuf message protocol.chat.v1.AddGuildToGuildListRequest
 */
class AddGuildToGuildListRequest$Type extends MessageType<AddGuildToGuildListRequest> {
  constructor() {
    super("protocol.chat.v1.AddGuildToGuildListRequest", [
      { no: 1, name: "guild_id", kind: "scalar", T: 4 /*ScalarType.UINT64*/ },
      { no: 2, name: "homeserver", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
    ]);
  }
}
export const AddGuildToGuildListRequest = new AddGuildToGuildListRequest$Type();
/**
 * Type for protobuf message protocol.chat.v1.AddGuildToGuildListResponse
 */
class AddGuildToGuildListResponse$Type extends MessageType<AddGuildToGuildListResponse> {
  constructor() {
    super("protocol.chat.v1.AddGuildToGuildListResponse", []);
  }
}
export const AddGuildToGuildListResponse = new AddGuildToGuildListResponse$Type();
/**
 * Type for protobuf message protocol.chat.v1.RemoveGuildFromGuildListRequest
 */
class RemoveGuildFromGuildListRequest$Type extends MessageType<RemoveGuildFromGuildListRequest> {
  constructor() {
    super("protocol.chat.v1.RemoveGuildFromGuildListRequest", [
      { no: 1, name: "guild_id", kind: "scalar", T: 4 /*ScalarType.UINT64*/ },
      { no: 2, name: "homeserver", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
    ]);
  }
}
export const RemoveGuildFromGuildListRequest = new RemoveGuildFromGuildListRequest$Type();
/**
 * Type for protobuf message protocol.chat.v1.RemoveGuildFromGuildListResponse
 */
class RemoveGuildFromGuildListResponse$Type extends MessageType<RemoveGuildFromGuildListResponse> {
  constructor() {
    super("protocol.chat.v1.RemoveGuildFromGuildListResponse", []);
  }
}
export const RemoveGuildFromGuildListResponse = new RemoveGuildFromGuildListResponse$Type();
/**
 * Type for protobuf message protocol.chat.v1.BanUserRequest
 */
class BanUserRequest$Type extends MessageType<BanUserRequest> {
  constructor() {
    super("protocol.chat.v1.BanUserRequest", [
      { no: 1, name: "guild_id", kind: "scalar", T: 4 /*ScalarType.UINT64*/ },
      { no: 2, name: "user_id", kind: "scalar", T: 4 /*ScalarType.UINT64*/ },
    ]);
  }
}
export const BanUserRequest = new BanUserRequest$Type();
/**
 * Type for protobuf message protocol.chat.v1.KickUserRequest
 */
class KickUserRequest$Type extends MessageType<KickUserRequest> {
  constructor() {
    super("protocol.chat.v1.KickUserRequest", [
      { no: 1, name: "guild_id", kind: "scalar", T: 4 /*ScalarType.UINT64*/ },
      { no: 2, name: "user_id", kind: "scalar", T: 4 /*ScalarType.UINT64*/ },
    ]);
  }
}
export const KickUserRequest = new KickUserRequest$Type();
/**
 * Type for protobuf message protocol.chat.v1.UnbanUserRequest
 */
class UnbanUserRequest$Type extends MessageType<UnbanUserRequest> {
  constructor() {
    super("protocol.chat.v1.UnbanUserRequest", [
      { no: 1, name: "guild_id", kind: "scalar", T: 4 /*ScalarType.UINT64*/ },
      { no: 2, name: "user_id", kind: "scalar", T: 4 /*ScalarType.UINT64*/ },
    ]);
  }
}
export const UnbanUserRequest = new UnbanUserRequest$Type();
