// @generated by protobuf-ts 1.0.12 with parameters long_type_string,optimize_code_size,generate_dependencies
// @generated from protobuf file "chat/v1/postbox.proto" (package "protocol.chat.v1", syntax proto3)
// tslint:disable
import { MessageType } from "@protobuf-ts/runtime";
/**
 * @generated from protobuf message protocol.chat.v1.SyncRequest
 */
export interface SyncRequest {
  /**
   * @generated from protobuf field: string token = 1;
   */
  token: string;
  /**
   * @generated from protobuf field: string host = 2;
   */
  host: string;
}
/**
 * @generated from protobuf message protocol.chat.v1.SyncEvent
 */
export interface SyncEvent {
  /**
   * @generated from protobuf oneof: event
   */
  event:
    | {
        oneofKind: "dmInvite";
        /**
         * @generated from protobuf field: protocol.chat.v1.SyncEvent.DMInvite dm_invite = 1;
         */
        dmInvite: SyncEvent_DMInvite;
      }
    | {
        oneofKind: undefined;
      };
}
/**
 * @generated from protobuf message protocol.chat.v1.SyncEvent.DMInvite
 */
export interface SyncEvent_DMInvite {
  /**
   * @generated from protobuf field: string user_name = 1;
   */
  userName: string;
  /**
   * @generated from protobuf field: string user_avatar = 2;
   */
  userAvatar: string;
  /**
   * @generated from protobuf field: string dm_name = 3;
   */
  dmName: string;
  /**
   * @generated from protobuf field: string dm_avatar = 4;
   */
  dmAvatar: string;
  /**
   * @generated from protobuf field: string invite_id = 5;
   */
  inviteId: string;
}
/**
 * Type for protobuf message protocol.chat.v1.SyncRequest
 */
class SyncRequest$Type extends MessageType<SyncRequest> {
  constructor() {
    super("protocol.chat.v1.SyncRequest", [
      { no: 1, name: "token", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
      { no: 2, name: "host", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
    ]);
  }
}
export const SyncRequest = new SyncRequest$Type();
/**
 * Type for protobuf message protocol.chat.v1.SyncEvent
 */
class SyncEvent$Type extends MessageType<SyncEvent> {
  constructor() {
    super("protocol.chat.v1.SyncEvent", [
      {
        no: 1,
        name: "dm_invite",
        kind: "message",
        oneof: "event",
        T: () => SyncEvent_DMInvite,
      },
    ]);
  }
}
export const SyncEvent = new SyncEvent$Type();
/**
 * Type for protobuf message protocol.chat.v1.SyncEvent.DMInvite
 */
class SyncEvent_DMInvite$Type extends MessageType<SyncEvent_DMInvite> {
  constructor() {
    super("protocol.chat.v1.SyncEvent.DMInvite", [
      { no: 1, name: "user_name", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
      {
        no: 2,
        name: "user_avatar",
        kind: "scalar",
        T: 9 /*ScalarType.STRING*/,
      },
      { no: 3, name: "dm_name", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
      { no: 4, name: "dm_avatar", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
      { no: 5, name: "invite_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
    ]);
  }
}
export const SyncEvent_DMInvite = new SyncEvent_DMInvite$Type();
